name: publish

on:
  release:
    types: [released]

jobs:
  release:
    environment:
      name: pypi
      url: https://pypi.org/project/nompy/${{ steps.inspect_package.outputs.version }}
    runs-on: ubuntu-latest
    outputs:
      package-version: ${{ steps.inspect_package.outputs.version }}
    permissions:
      id-token: write
    steps:
      - uses: actions/checkout@v4
      - uses: astral-sh/setup-uv@v5
        with:
          version: "0.7.3"
          enable-cache: true
      - run: uv build
      - name: inspect-version
        id: inspect_package
        run: |
          uv tool install --with uv-dynamic-versioning hatchling
          version=$(uvx hatchling version)
          echo "version=$version" >> "$GITHUB_OUTPUT"
      - name: publish
        uses: pypa/gh-action-pypi-publish@release/v1
        with:
          skip-existing: true
